console.log(null==undefined);
console.log(undefined<0);
console.log("23">"177");
console.log("23">177);
console.log("01"==1);
console.log("1"===1);
console.log(null==0);
console.log(null===0);
console.log("mango">90);